id = "snipas"
name = "Snippets Assorted"
version = "0.1.0"
schema_version = 1
description = "A collection of useful code snippets for various languages"
repository = "https://github.com/tsilvs/snipas"
authors = ["tsilvs <tsilvs542@gmail.com>"]
themes = []
icon_themes = []
languages = []
snippets = [
	"./snippets/javascript.json",
	"./snippets/json.json",
	"./snippets/markdown.json",
	"./snippets/org.json",
	"./snippets/shell script.json",
	"./snippets/snippets.json",
	"./snippets/typescript.json",
]

capabilities = []

[lib]

[grammars]

[language_servers]

[context_servers]

[slash_commands]

[indexed_docs_providers]
